### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by Davichet-e** [InternetHealthReport/gsoc#1]
Hello everyone, I just followed this link here
![Captura de pantalla 2022-04-04 213627](https://user-images.githubusercontent.com/48657914/161618944-33302d35-fe18-4991-9aca-c7edf043cf6b.png)

At the [ideas file](https://github.com/InternetHealthReport/gsoc/blob/main/ideas.md#port-link-monitoring-code-to-python3-and-kafka), and it seems broken, since it just redirects to the home page.

Thank you for your time. Regards

**Comment by romain-fontugne** [comment]
Thanks, IIJ-II changed its website to IIJLab on April 1st. I have updated the links in the list of ideas

**Comment by Gairick52** [comment]
@Davichet-e i am new to open source can you suggest me some beginner friendly issues
