### ISSUE TITLE
Links position is uneven at homepage

### ISSUE THREAD

**Issue by Ahamad-Tanzeel-Khan** [InternetHealthReport/gsoc#10]
![1](https://user-images.githubusercontent.com/117995820/230756995-43e8a029-8356-4803-a995-b86460d10111.PNG)

**Comment by romain-fontugne** [comment]
Feel free to fix this if you want

**Comment by rishi803** [comment]
I want to contribute. Would you please assign me this or simply I can start contributing. I am new to open source.

**Comment by romain-fontugne** [comment]
Sure, go ahead

**Comment by performant23** [comment]
Hey, where can the source code for the website be accessed? @romain-fontugne (in case the issue isn't solved)?

**Comment by romain-fontugne** [comment]
The source code for the website is here: https://github.com/InternetHealthReport/ihr-website

**Comment by khadar1020** [comment]
can i solve this issue @romain-fontugne

**Comment by romain-fontugne** [comment]
I don't think anyone is working on this, go for it @khadar1020

**Comment by MAVRICK-1** [comment]
Will solve within an hour

**Comment by khadar1020** [comment]
This issue is solved @MAVRICK-1 and reviewing of PR is only pending

**Comment by MAVRICK-1** [comment]
Bro my website is not setting up locally can you help me?

**Comment by horizenight** [comment]
@romain-fontugne Kindly close this issue as it is resolved in this PR #640
