### ISSUE TITLE
Documentation fig.1 Overview of the Internet Alice sends an email to Bob is not render 

### ISSUE THREAD

**Issue by MAVRICK-1** [InternetHealthReport/gsoc#33]
![IMG_20231203_102009](https://github.com/InternetHealthReport/gsoc/assets/146999057/3fc49053-e3e9-4b4d-a34f-8c70eba99b36)
The Internet Health Report: Handbook for Contributors at 2.1 section The basics of Internet routing ,  the diagram to show , __Overview of the Internet. Alice sends an email to Bob (red dashed lines) and browses github’s website.__ not render.

**Comment by romain-fontugne** [comment]
it does render for me:
![image](https://github.com/InternetHealthReport/gsoc/assets/1373917/2fbf5587-b48b-4418-988d-b355c261d842)

are you using any plugin that would block that?

**Comment by horizenight** [comment]
It does render for me also. 👍🏼

**Comment by romain-fontugne** [comment]
I'm closing this because I cannot reproduce it
