### ISSUE TITLE
What's the project size of "Dockerize IHR components" ?

### ISSUE THREAD

**Issue by 0xMostafa** [InternetHealthReport/gsoc#8]
what's the project size of this project ([here](https://github.com/InternetHealthReport/gsoc/blob/main/ideas.md#dockerize-all-ihr-components)) ?

is it medium (175 hours) or hard (350 hours)?

**Comment by romain-fontugne** [comment]
I expect this is going to be a smaller project (175 hours) but if you think that it needs more time then you can explain why in your proposal
